"""Generative-model teaching implementations and public benchmark utilities."""

from .data import DatasetMetadata, LatentDigits, MNISTData, load_latent_digits, load_mnist
from .evaluation import evaluate_generator, frechet_gaussian_distance, rbf_mmd_squared
from .models import (
    AffineCouplingLayer,
    ConditionalFlowMatcher,
    ConditionalMNISTFlowMatcher,
    ConditionalMNISTVAE,
    ConditionalMNISTVAEModel,
    DenoisingDiffusion,
    GaussianAffineFlow,
    GaussianVAE,
    MNISTVelocityCNN,
    SUPPORTED_TORCH_DEVICES,
    TimeConditionedMLP,
    TorchVectorRegressor,
    TutorialVelocityMLP,
    TwoMoonsFlowMatcher,
    VectorVAE,
    diagonal_gaussian_kl,
    linear_beta_schedule,
    make_diffusion_training_data,
    make_flow_matching_training_data,
    resolve_torch_device,
)

__all__ = [
    "AffineCouplingLayer",
    "ConditionalFlowMatcher",
    "ConditionalMNISTFlowMatcher",
    "ConditionalMNISTVAE",
    "ConditionalMNISTVAEModel",
    "DatasetMetadata",
    "DenoisingDiffusion",
    "GaussianAffineFlow",
    "GaussianVAE",
    "LatentDigits",
    "MNISTData",
    "MNISTVelocityCNN",
    "SUPPORTED_TORCH_DEVICES",
    "TimeConditionedMLP",
    "TorchVectorRegressor",
    "TutorialVelocityMLP",
    "TwoMoonsFlowMatcher",
    "VectorVAE",
    "diagonal_gaussian_kl",
    "evaluate_generator",
    "frechet_gaussian_distance",
    "linear_beta_schedule",
    "load_latent_digits",
    "load_mnist",
    "make_diffusion_training_data",
    "make_flow_matching_training_data",
    "rbf_mmd_squared",
    "resolve_torch_device",
]
